yoda_event_event:
    resource: "@YodaEventBundle/Resources/config/routing/event.yml"
    prefix:   /event

yoda_event_homepage:
    path:     /hello/{firstName}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }
